### ISSUE TITLE
Make a "total lines of code written" badge

### ISSUE THREAD

**Issue by fffelix-jan** [puf17640/git-badges#25]
Please make a badge that would show how many lines of code you have uploaded to GitHub in total. Thanks!

**Comment by puf17640** [comment]
> Please make a badge that would show how many lines of code you have uploaded to GitHub in total. Thanks!

I dont think there is a way to easily get to that metric and adding up the line count of every file in every repo you have doest make sense since many repositories are built by more than 1 person which would then change the result. If you have the means of getting said metric, please either feel free to contribute the endpoint yourself or share your sources 👍
